version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution_db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    container_name: evolution_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass evolution_redis_pass
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # Evolution API
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - postgres
      - redis

volumes:
  evolution_instances:
  postgres_data:
  redis_data:
